---
title: "SLAB Legal Aid Model Documentation"
date: May/20/2024
authors:
  - name: Graham Stark
    affiliation: Virtual Worlds Research
    email: graham.stark@virtual-worlds.scot
citation:
  url: https://virtual-worlds.scot/techdoc/index.html
bibliography: SLAB-2024.bib
csl: /home/graham_s/pandoc_data/chicago-note-bibliography.csl
# engine: julia
jupyter: julia-1.10
---
```{julia}

#| echo: false
#| warning: false
#| output: false

using DataFrames, CairoMakie, CSV, StatsBase, GLM, Revise 
using ScottishTaxBenefitModel
using .Definitions
using .FRSHouseholdGetter
using .RunSettings
using .ConsumptionData
using .LegalAidData

settings = Settings()

fig_width = 600
fig_height = fig_width*3/4
Makie.update_theme!(theme_ggplot2()) #; size = (fig_width, fig_height))

hh_dataset = CSV.File( joinpath(settings.data_dir,settings.household_name*".tab" )) |> DataFrame
people_dataset = CSV.File( joinpath( settings.data_dir, settings.people_name*".tab")) |> DataFrame

```


## Introduction

These are technical notes for the for the Scottish Legal Aid Board eligibility simulator model.

For an overview of the purpose and desired specifications of the model, please refer to the SLAB bid document and the Virtual Worlds tender document. For an overview of the legal aid system itself, see [???] Broadly, purpose of the model is to estimate the entitlement to both Civil and Advice and Assistance (AA) legal aid amongst the Scottish Population under the current and various hypothetical systems, and from that estimate the likely costs or savings of changes to eligibility rules. 

The LASim model that was built do do this built on earlier work for the England And Wales Legal Aid Board [@buck_means_2001;@buck_simplicity_2003;] and the Scottish and Northern Irish Legal Aid Boards [@digan_financial_2007;@StarkSLAB]. 

## The Model

### Code organisation

LASim builds on [Scotben](https://github.com/grahamstark/ScottishTaxBenefitModel.jl/), a microsimulation tax-benefit model of Scotland. Scotben is a conventional static microsimulation model, built using the [Julia](https://juliahub.org) programming language and Family Resources Survey (FRS) [] data. 

A tax benefit model is [..]. For more information on this model, see [] and for tax-benefit models generally, see [].

All the code used in this project is available for inspection on the GitHub code sharing site, as follows:

* [Scotben - the Main Model](https://github.com/grahamstark/scottishtaxbenefitmodel.jl)
* [LASim - the web Front End](https://github.com/grahamstark/lainterfaces/)

Julia code is organised into `modules` [] which are aggregated into packages []. Packages can be downloaded and either run directly or integrated into other programs. ScotBen is a Julia package. For this project, several modules were added to the Scotben package:

* [LegalAidCalculations.jl](https://github.com/grahamstark/ScottishTaxBenefitModel.jl/blob/master/src/LegalAidCalculations.jl) - this calculates entitlement to both Civil and AA for a single FRS household.  
* [LegalAidOutput.jl](https://github.com/grahamstark/ScottishTaxBenefitModel.jl/blob/master/src/LegalAidOutput.jl) - this generates output tables and calculates the likelyhood that a given household will claim legal aid.
* [LegalAidData.jl](https://github.com/grahamstark/ScottishTaxBenefitModel.jl/blob/master/src/LegalAidData.jl) - this holds SLAB supplied individual-level records for payments and contributions under both Civil and AA legal aid. This is used along with tbe entitlement data to produce cost and takeup estimates. 

in addition, additions were made to the following Modules:

* [STBParameters.jl](https://github.com/grahamstark/ScottishTaxBenefitModel.jl/blob/master/src/STBParameters.jl) - this models the parameters needed for the entire Scottisg/UK fiscal system - tax rates, benefit levels and so on. A set of parameters capturing capital and income limits, rules for allowances, disregarded incomes, etc. was added 
* [Results.jl](https://github.com/grahamstark/ScottishTaxBenefitModel.jl/blob/master/src/Results.jl) - This holds records capturing entitlements to benefits, liability to tax, etc. for a single household. A record capturing entitlement to Legal Aid, contributions, assessed income, etc. was added, as `OneLegalAidResult`.
* [SingleHouseholdCalculations.jl](https://github.com/grahamstark/ScottishTaxBenefitModel.jl/blob/master/src/SingleHouseholdCalculations.jl) - this runs all calculations for all FRS households. A small call was added to optionally run the legal aid calculations; 
* [STBOutput](https://github.com/grahamstark/ScottishTaxBenefitModel.jl/blob/master/src/STBOutput.jl) - this holds the main output from the model. The structures from `LegalAidOutput` are incorporated here.
* [RunSettings](https://github.com/grahamstark/ScottishTaxBenefitModel.jl/blob/master/src/RunSettings.jl) - fields were added to control optional switching of the capital source - this is discussed below.  

In addition, considerable development time was spent on the module [LegalAidRunner.jl](https://github.com/grahamstark/ScottishTaxBenefitModel.jl/blob/master/src/LegalAidRunner.jl) which was intended to be a specialised high-speed driver module for legal aid calculations. This module was eventually abandoned because its memory requirements were too mich for the relatively underpowered laptop chosen to host the model.

### Taxes and Benefits

The 2007 model was custom-written to specifically model Legal Aid. Instead of calculating liability to taxes and entitlements to benefits, it instead simply took recorded FRS values for these things and used those in its LA calculations. The current system is a general purpose tax-benefit model which makes it's own estimates of household liabilities and entitlements given the rules of the fiscal system. We chose this approach chiefly because the benefit system, in particular, is changing rapidly, especially with the phased introduction of Universal Credit. To model Scotland with reasonable accuracy, you need to 'pool' multiple years of FRS data and, unless you override recorded benefit receipts with values calculated on the current regime, older data becomes unrepresentative. (The same is true of direct taxes though this is less relevant to Legal Aid Calculations).

::: {.callout-note}
There are two issues with benefits:

* we use modelled entitlements rather than recorded receipts. There are currently no official estimates of means-tested benefit takeup (it is deemed too complex because of the legacy/UC transition) but previous estimates were of the range 50-80% [^@], 
* the transition from Legacy Benefits [] to Universal Credit is progressing and this is hard to capture accurately. [Our modelling of this](https://github.com/grahamstark/ScottishTaxBenefitModel.jl/blob/master/src/UCTransition.jl) is based on analysis by the House Of Commons Library[@house_of_commons_library_constituency_2020].

:::

Specification of the legal aid system came from the following documents:
* 
*
*


### Calibration


### Testing 

Core code is created test-first []. Material for the tests came mainly from the online Legal Aid Calculators [][]. The spreadsheet 
[][] contains the raw test cases, which were translated into the testsuite ``[]. The testsuite also contains a number of "dry runs" of the model.

::: {.callout-note}
The test suite is not as comprehensive as it should be. Quite a serious mistake in how capital is treated for passporting in AA slipped through unchecked until late in the development process. Mistakes in which benefits are disregarded also slipped though until late on. 
:::
### Web Interface

The model has a web user interface. The code for this is in the LASim package. This is effectively the main package for the system, though legal aid simulations can actually be run directly from the `Scotben` package, or from any code that imports `ScotBen`. 

The package uses the [Genie](https://genieframework.com/) web framework. Genie provides much of the messy back-end needed for a web application, such as a simple web-server, the facility to start sessions for users and the like. Building on this, LASim is a single-page application which uses a large amount of hand-written Javascript to handle submissions and responses. Styling uses the [Bootstrap](https://getbootstrap.com/) css framework, customised to use SLAB fonts and colours. 

::: {.callout-note}
There are several issues with the front-end:

* the front-end package needs rationalised. The package includes not only the actual front-end but two earlier abortive attempts at interfaces for the model. Only the `LASim` subfolder is actually needed;
* the front-end is probably too big for a single page. It should either be broken up or aspects of inputs and outputs should be hidden by default
* the interface code is hand-written and close to the limit of what can be maintained by hand-coding. A more automated system would be needed if many more options were added;
* there are problems with the interface's performance on the rather limited SLAB laptop supplied for running it;
* the monitoring `progress bar` code was added last-minute and is somewhat unreliable.

:::


### FRS Data

The model uses the Scottish households from pooled 2015-2021 Family Resources (FRS) data[@department_for_work_and_pensions_family_2024]. We use the public use FRS release which has a number of fields deleted for privacy reasons, though the deletions often seem arbitrary. 

### Matching 

The FRS is augmented with matched in data from the Scottish Household Survey[@scottish_government_scottish_2024-1] and the Living Costs and Food Survey. SHS is mainly used to give local-level information and is not very relevant to Legal Aid. LCF is used to provide estimates for some of the expense fields - repayments, travel to work costs and work expenses. The matching code for thse dataset is [the matching/ folder](https://github.com/grahamstark/ScottishTaxBenefitModel.jl/tree/master/matching). Matching uses a custom version of Coarsened Exact Matching [@iacus_causal_2011; @leulescu_statistical_2013; @dorazio_statmatch_2022] 

Both LCF and SHS are matched to FRS at the household level.

The SHS/FRS are matched on:
* Tenure Type
* Accomodation Type
* Single Parent
* Num Adults
* Num Children
* Employment Status of Head of Household (HoH)
* Socio-Economic Status of HoH
* Age of HoH
* Ethnic Group Of HoH 

LCF/FRS are matched on:

* Tenure Type
* Accomodation Type
* Number of Rooms
* Age of Head
* Num Children
* Is self employed
* Num children
* Num adults
* Ethnic Group (White/Non-White)
* Age of HoH
* Ethnic Group Of HoH 

The 'top 20' matches on these variables are then ranked by household income. 

Code for this is in the [MatchingLibs.jl module](https://github.com/grahamstark/ScottishTaxBenefitModel.jl/blob/master/src/MatchingLibs.jl)

#### Capital

```julia 

# from MakeHousehold
 model_adult.wealth_and_assets = frs_bu.totcapb3
            # we'll also store the band 
            model_adult.totsav= frs_bu.totsav

"""
return 3 element vector 1=financial, 2=physical 3=housing 4=pension
"""
function add_wealth!( 
    intermed  :: MTIntermediate{T},
    hh        :: Household{T},
    bu        :: BenefitUnit,
    buno      :: Int,
    method    :: ExtraDataMethod ) where T
    if method == imputation 
        if buno == 1 # use the regression hhld stuff from was & assign all to 1st bu 
            intermed.net_financial_wealth = hh.net_financial_wealth
            intermed.net_physical_wealth = hh.net_physical_wealth
            intermed.net_housing_wealth  = hh.net_housing_wealth 
            intermed.net_pension_wealth = hh.net_pension_wealth
        end
    elseif method == matching
        @assert false "FRS matching not implemented yet for get_wealth"
    elseif method == no_method
        head = get_head( bu )
        # println( "add_wealth! method=$method head.wealth_and_assets=$(head.wealth_and_assets)")
        intermed.net_financial_wealth = head.wealth_and_assets
        # nothing else set
    elseif method == other_method_1
        head = get_head( bu )
        cap = map_totsav(
            head.totsav,
            hh.data_year,
            head.wealth_and_assets,
            head.onerand )
        intermed.net_financial_wealth = cap
        intermed.net_physical_wealth = cap*0.6 # average diff between financial and physical in WAS
    end
end
```

[@office_for_national_statistics_wealth_2017]

#### Expenses

* Housing - for owner occupiers the FRS normally just counts mortgage interest as a cost. We add in capital repayments though this is tricky to derive from FRS variables. Code is in `xx` function in the `xxx` library. 
* Maintenance payments  - ??
* Debt repayments - use matched LCF data - COICOP code [XXX].

::: {.callout-note}

Expense fields seem low. It is known that average expenses for maintenance contributions, debt repayments and work expenses are much lower on average in the FRS than in SLAB administrative data. This may simply be a selection problem but needs more investigation. Debt in particular could be reworked. Note that student loans are mostly paid through income tax and thus automatically deducted from the model's income tax calculation.
:::

### Scottish Crime and Justice Survey (SCJS)

As an aside, the original proposal was to use SCJS[@scottish_government_scottish_crime_2024] to model the likelihood of households experiencing a problem requiring legal advice. Some initial work was carried out which produced promising but this was abandoned on SLAB's instructions. It could well be worth returning to this, perhaps as a stand-alone piece of work.  

### SLAB Datasets

Anonymised versions of the complete SLAB Civil and AA payments data for 2022/3 were supplied. These are the files XX and XX. 
These were used in the production of cost and caseload estimates. The procedure is crude, but the same as used in the 2007 study. The module `LegalAidData.jl` crosstabs the payment data by age group, sex/gender, case type, and entitlement level (passported/full entitlement/with contribition) and these are matched against crosstabs from the model by age/sex/estimated entitlement level to give estimates of the propensity of each entitlement group to claim legal aid. This is a crude procedure which at times produces questionable results such as the propensities for contributory benefit units sometimes being higher than for passported/fully entitled benefit units.    

### Updating and Maintenance

### TODODs

```{julia}

#| echo: false
#| warning: false

threeplot( 
  hh_dataset.net_financial_wealth, 
  hh_dataset.total_wealth, xlabel="FRS Financial Wealth", ylabel="WAS Modelled Financial Wealth")

# with_theme(f, theme_ggplot2())
```

```{julia}

```


### References

::: {#refs}
:::
